### ISSUE TITLE
Switch to use HTTPoison

### ISSUE THREAD

**Issue by richleland** [SparkPost/elixir-sparkpost#12]
Because it's fly - https://github.com/edgurgel/httpoison

**Comment by DavidAntaramian** [comment]
@richleland I can take care of this if you want :)

**Comment by richleland** [comment]
hell yeah go for it @DavidAntaramian !

**Comment by DavidAntaramian** [comment]
@ewandennis is there a specific reason you chose to implement `SparkPost.Endpoint.request/3` with options as a `Keyword` instead of a `Map`?

**Comment by ewandennis** [comment]
@DavidAntaramian - pure oversight.  Very happy to accept a PR.  Otherwise I'll do a pass on this project when I clear my desk next.

**Comment by DavidAntaramian** [comment]
@ewandennis I'll include it in this PR since it's easier to implement HTTPoison change with a map.
