### ISSUE TITLE
Impossible to use with Phoenix due version mistmatch

### ISSUE THREAD

**Issue by programisti** [SparkPost/elixir-sparkpost#43]
when running `mix deps.get` mix throws an error
```Failed to use "poison" (versions 1.5.0 to 2.2.0) because
  phoenix (version 1.2.4) requires ~> 1.5 or ~> 2.0
  sparkpost (version 0.5.0) requires ~> 3.0
```
because sparkpost requires poison of version 3.0 and phoenix requires somewere between 1.5 to 2.2
I forked and lwoered poison version to 2.2.0 and it works
https://github.com/programisti/elixir-sparkpost

**Comment by ewandennis** [comment]
Yup, fair point until we see Phoenix 1.3 ;) Relaxing that requirement. Thanks for the report! @programisti
