### ISSUE TITLE
Transmission.get no longer supported?

### ISSUE THREAD

**Issue by mstratman** [SparkPost/elixir-sparkpost#47]
Version: using 0.5.1 from hex.

Actual:
```
iex(103)> SparkPost.Transmission.get("156823913470671414")
%SparkPost.Endpoint.Error{errors: [%{message: "You may use the Message Events API to retrieve event data for your transmission. For example https://api.sparkpost.com/api/v1/message-events?from=2018-01-05T03:00&transmission_ids=156823913470671414"}],
 results: nil, status_code: 404}
```

Expected:
Results like the following: https://github.com/SparkPost/elixir-sparkpost/blob/5f4382830fc1059a158be24e2897d5f7b3bd3c73/lib/transmission.ex#L140-L150

**Comment by avigoldman** [comment]
Hey @mstratman 👋 The transmission [get endpoint](https://developers.sparkpost.com/api/transmissions.html#transmissions-retrieve-and-delete-get) is only for retrieving scheduled transmissions. If you are trying to get info about the emails that were sent, you can query the message events API.

**Comment by mstratman** [comment]
Got it. Thank you!
