### ISSUE TITLE
use httpoison 1.x

### ISSUE THREAD

**Issue by jasongoodwin** [SparkPost/elixir-sparkpost#48]
currently uses an older version of httpoison

**Comment by jasongoodwin** [comment]
I bumped the dependency here: 
https://github.com/SparkPost/elixir-sparkpost/pull/49

**Comment by jasongoodwin** [comment]
Any updates?

**Comment by ewandennis** [comment]
Resolved in [0.5.2 release](https://hex.pm/packages/sparkpost/0.5.2). Thanks!

**Comment by jasongoodwin** [comment]
thanks!
